language: php

php:
  - 5.5
  - 5.6

env:
  matrix:
    - TYPO3_VERSION="~7.6.0"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - composer --version
  - composer global require fabpot/php-cs-fixer

install: Tests/Build/bootstrap.sh
script: Tests/Build/cibuild.sh
after_script: Tests/Build/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
